Update pegs.nim to work at compiletime. No range errors.
nim-lang/Nim pull request #13459
Opened 2020-02-21 17:11 UTC by solo989

2020-02-25 20:57 UTC, krux02 commented
test case is missing. The best way to test this is to transform an already existing pegs test into a test that runs both at run time as well as at compile time.

2020-02-26 21:42 UTC, solo989 commented
Added a testcase.

2020-02-26 22:21 UTC, krux02 requested changes

2020-02-26 22:21 UTC, krux02 commented on lib/pure/pegs.nim
> +    assert match("(a b c)", peg"'(' @ ')'")
Here is an example how to lift a test to be executed at compile time as well as runtime:
https://github.com/nim-lang/Nim/blob/devel/tests/stdlib/tjsonmacro.nim#L638

2020-02-26 23:40 UTC, solo989 commented
Lifted all tests.

2020-02-27 00:58 UTC, krux02 approved these changes

2020-02-27 10:08 UTC, merged