Fix logging tiny bug
nim-lang/Nim pull request #14910
Opened 2020-07-05 10:10 UTC by juancarlospaco

- Changed `maxLines` to `Positive` on `logging.newRollingFileLogger`,
  because negative values cause 1 new file per line of log, and make no sense whatsoever.
- Changed `log` on `logging` to use proper log level on JavaScript target,
  eg. `debug` uses `console.debug`, `info` uses `console.info`, `warn` uses `console.warn`, etc.
- Internal proc `countLogLines` simplified.

You can check the Bug with this code:
```nim
import logging
var rollingLog = newRollingFileLogger("rolling.log", maxLines = -9)
addHandler(rollingLog)
for _ in 0..99: info "42"
```

:)

2020-07-05 10:12 UTC, Yardanico commented on changelog.md
> +- Changed `maxLines` to `Positive` on `logging.newRollingFileLogger`,
```suggestion
- Made `maxLines` argument `Positive` in `logging.newRollingFileLogger`,
```

2020-07-05 10:12 UTC, Yardanico commented on changelog.md
> +  because negative values cause 1 new file per line of log, and make no sense whatsoever.
```suggestion
  because negative values will result in 1 new file being created for each logged line which doesn't make sense.
```

2020-07-05 10:13 UTC, Yardanico commented on changelog.md
> +- Changed `log` on `logging` to use proper log level on JavaScript target,
```suggestion
- Changed `log` in `logging` to use proper log level on JavaScript target,
```

2020-07-06 06:41 UTC, Varriount requested changes

2020-07-06 06:41 UTC, Varriount commented on lib/pure/logging.nim
> +    readFile(logger.baseName).countLines()
Hm, doesn't this read in the entire file though? That might cause some pretty large allocations in some circumstances.

2020-07-06 08:00 UTC, merged