Improve httpClient docs on SSL cert verification
nim-lang/Nim pull request #15201
Opened 2020-08-18 10:31 UTC by FedericoCeratto

A small doc improvement

2020-08-21 21:51 UTC, dom96 requested changes

2020-08-21 21:51 UTC, dom96 commented on lib/pure/httpclient.nim
> +## .. code-block:: Nim
Please write a little blurb to introduce this example, otherwise it's just an example without any context.

2020-08-21 21:51 UTC, dom96 commented on lib/pure/httpclient.nim
> +## locate certificates
```suggestion
##   * ``CVerifyNone``: certificates are not verified;
##   * ``CVerifyPeer``: certificates are verified;
##   * ``CVerifyPeerUseEnvVars``: certificates are verified and the optional
##     environment variables SSL_CERT_FILE and SSL_CERT_DIR are also used to
##     locate certificates
```

2021-06-13 14:17 UTC, FedericoCeratto commented on lib/pure/httpclient.nim
> +## .. code-block:: Nim
Done

2021-06-13 15:50 UTC, merged