fix https://github.com/nim-lang/Nim/issues/15413: support JSON in int64.high+1..uint64.high
nim-lang/Nim pull request #15545
Opened 2020-10-10 21:32 UTC by timotheecour

fix https://github.com/nim-lang/Nim/issues/15413

2020-10-20 00:25 UTC, disruptek commented
How does deprecation work?

2020-10-20 02:37 UTC, timotheecour commented
> How does deprecation work?

see https://github.com/nim-lang/Nim/pull/15646 for my proposal

2020-10-21 23:42 UTC, timotheecour commented
PTAL, green now

2020-10-28 08:35 UTC, jackhftang commented
Please consider carefully before adding any new JSON kind! If you regret later, this will be a breaking change. This cannot be undone and the interface will ruin.

2020-10-28 19:53 UTC, dom96 requested changes
**This will break code**, we shouldn't merge it until it there is a transition path.

2020-10-28 21:27 UTC, timotheecour commented
> This will break code, we shouldn't merge it until it there is a transition path.

I've suggested https://github.com/nim-lang/Nim/pull/15646 but this was closed, and I've also suggested affected code be patched with trailing else which is forward and backward compatible, ie after the trailing else is added to affected code it will work with both new and old enum.

What is your alternative suggestion to fix #15413 and make nim parse valid json strings involving numbers (eg uint64 that don't fit int64, or beyond uint64/int64/float64) ?

2020-10-29 07:07 UTC, Araq commented
> which can't distinguish string from unparsable numbers 

It can do that... Not that it's a big deal anyway.

2020-10-29 07:07 UTC, closed without merging