Fix #15706
nim-lang/Nim pull request #15846
Opened 2020-11-05 11:22 UTC by bung87

2020-11-06 19:09 UTC, cooldome requested changes
I have reviewed the changes. Actually approach needs to be a little bit different.
Find invocation of `binaryArithOverflowRaw` from `genMagicExpr`. `binaryArithOverflowRaw` is called with type `ranged`. Like this:
```nim
      let ranged = skipTypes(e[1].typ, {tyGenericInst, tyAlias, tySink, tyVar, tyLent, tyDistinct})
      let res = binaryArithOverflowRaw(p, ranged, ....)
```
It needs to be
```nim
      let ranged = skipTypes(e[1].typ, {tyGenericInst, tyAlias, tySink, tyVar, tyLent, tyDistinct})
      let res = binaryArithOverflowRaw(p, ranged, ....)
```

2020-11-06 19:11 UTC, cooldome commented
I confirm that have reviewed all the places where overflow checks actually made, distinct types are handled everywhere including jsgen exception. This is the only place where checks for distinct types where missing.

2020-11-06 19:22 UTC, cooldome commented on tests/overflw/tdistinct_range.nim
> +  outputsub: "Error: unhandled exception: over- or underflow [OverflowDefect]"
better to use errormsg: "unhandled exception: over- or underflow"

2020-11-07 00:35 UTC, bung87 commented
Thanks for review my PR, am not sure am properly to change the error message, I checked the jsgen it doesn't even care of range, it only handle destinate type range.

2020-11-07 08:00 UTC, merged