algorithm.nim: Use `func`
nim-lang/Nim pull request #16304
Opened 2020-12-09 17:34 UTC by ee7

To confirm: do we want to change a `proc` that has a `proc` parameter into a `func`"? (See the first commit in this PR).

https://github.com/nim-lang/Nim/pull/16293 was merged, so I assume the answer is "yes".

This PR changes `sorted` from a `proc` to a `func`, but the below code will still compile without error even when using `--experimental:strictFuncs`.

```Nim
import algorithm

proc myCmp(x, y: int): int =
  echo "this is a side effect"
  if x == y: return 0
  if x < y: return -1
  return 1

let foo = sorted([2, 1, 3], myCmp)
echo foo
```

It produces:
```shell
this is a side effect
this is a side effect
this is a side effect
this is a side effect
@[1, 2, 3]
```

I just want to make sure that this is what we want.

See also: https://github.com/nim-lang/Nim/issues/16303

2020-12-09 18:16 UTC, timotheecour approved these changes

2020-12-09 18:18 UTC, timotheecour requested changes
hmm, I guess tests fail...

```
2020-12-09T17:51:16.8819350Z /Users/runner/work/1/s/lib/pure/algorithm.nim(434, 6) Error: 'sorted' can have side effects
2020-12-09T17:51:16.8836130Z an object reachable from 'a' is potentially mutated
2020-12-09T17:51:16.8863760Z /Users/runner/work/1/s/lib/pure/algorithm.nim(454, 8) the mutation is here
```

2020-12-09 18:27 UTC, ee7 commented
> hmm, I guess tests fail...

Yeah, it's due to:
https://github.com/nim-lang/Nim/blob/f344a704123a4b55e2b3b8a4f736a6739d0683bb/tests/views/tcan_compile_nim.nim#L2

Because this:
```shell
bin/nim c --experimental:strictFuncs compiler/nim.nim
```

doesn't work with `sorted` as `func`. I thought I checked that, but oh well.

Let's see what happens with `sorted` as a `proc`. But I don't know if that's the right fix.

2020-12-09 19:32 UTC, timotheecour commented
I've reduced the previous CI failure to https://github.com/nim-lang/Nim/issues/16305

2020-12-09 19:36 UTC, timotheecour approved these changes

2020-12-09 23:59 UTC, Araq commented
> To confirm: do we want to change a proc that has a proc parameter into a func?

No, it was an oversight by me. We don't want that. Callbacks can have effects.

2020-12-10 01:43 UTC, timotheecour commented
>> To confirm: do we want to change a proc that has a proc parameter into a func?

> No, it was an oversight by me. We don't want that. Callbacks can have effects.

That's the crux of https://github.com/nim-lang/Nim/issues/16303 and IMO we do want that:
`proc callCb(cb: proc(): int): int = result = cb()` is safe to change to 
`func callCb(cb: proc(): int): int = result = cb()`, as explained in https://github.com/nim-lang/Nim/issues/16303#issuecomment-742175297

2020-12-10 11:08 UTC, ee7 commented
> > To confirm: do we want to change a proc that has a proc parameter into a func?
> 
> No, it was an oversight by me. We don't want that. Callbacks can have effects.

I see. I should've asked explicitly in the sequtils PR description, rather than this one. Sorry.

Questions:
1. Could you complete this statement? "A `proc` in the standard library should eventually become a `func` if it satisfies all of the following conditions:"
1. Does anything currently block us from changing such procs into funcs?

2021-04-21 13:12 UTC, Araq commented
If you want to continue with this, the next steps would be:

- Compile talgorithm.nim with --strictFuncs:on.
- Write tests that check wether a `ref object` can be used as the `T` in `openArray[T]`.

2022-05-31 02:25 UTC, closed without merging