document #17208
nim-lang/Nim pull request #17236
Opened 2021-03-02 14:12 UTC by xflywind

2021-03-02 15:47 UTC, konsumlamm requested changes

2021-03-02 15:47 UTC, konsumlamm commented on lib/pure/parseutils.nim
> +  ## only the value of last fitting characters
```suggestion
  ## only the value of the last fitting characters
```

2021-03-02 15:47 UTC, konsumlamm commented on lib/pure/strutils.nim
> +  ## only the value of last fitting characters
```suggestion
  ## only the value of the last fitting characters
```

2021-03-02 17:40 UTC, timotheecour commented
This is just too weird, we should fix the bug instead of documenting this.

2021-03-03 00:15 UTC, juancarlospaco commented
Fixing the Bug would be better, doc looks Ok.

2021-03-03 07:04 UTC, closed without merging

2021-03-03 07:04 UTC, xflywind commented
it needs to be fixed instead