Added setutils.[]= variant
nim-lang/Nim pull request #17302
Opened 2021-03-08 22:37 UTC by beef331

Adds a variant of setutils.[]= which takes a whole set

2021-03-09 01:03 UTC, konsumlamm requested changes

2021-03-09 01:03 UTC, konsumlamm commented on lib/std/setutils.nim
> +  ## Syntax sugar for `if val: t.incl args else: t.excl args`,
```suggestion
  ## Syntax sugar for `if val: s.incl args else: s.excl args`,
```

2021-03-09 02:02 UTC, timotheecour approved these changes
LGTM

(in this or future PR, we should also change:
```nim
func `[]=`*[T](t: var set[T], key: T, val: bool) {.inline.} =
```

to 
```nim
func `[]=`*[T](s: var set[T], key: T, val: bool) {.inline.} =
```

2021-03-09 06:11 UTC, Araq commented
Do other languages support it? It does look a bit weird to be honest.

2021-03-09 08:05 UTC, timotheecour commented
> Do other languages support it? It does look a bit weird to be honest.

`set` support in other languages is rather limited though (closest thing is usually a notion of bit vector). Plausible options are:

put ?
putAll ?
[]= ?

(but keeping []= for the previous overload from https://github.com/nim-lang/Nim/pull/17272)

2021-03-11 13:12 UTC, Araq commented
Strong -1 from me, I cannot imagine a use case for this, seems like pure bloat. "Consistency" isn't a use case.

2021-03-21 09:43 UTC, Araq commented
Sorry, it simply looks too weird and it's unclear we need it.

2021-03-21 09:43 UTC, closed without merging