added more modules
nim-lang/Nim pull request #17430
Opened 2021-03-20 17:23 UTC by AFaurholt

Per [Issue #16656](https://github.com/nim-lang/Nim/issues/16656) I tried to add the missing modules to the list. I wasn't sure what to do with io or assertions since they're listed under [system](https://nim-lang.org/docs/system.html)

2021-03-20 18:01 UTC, konsumlamm requested changes

2021-03-20 18:01 UTC, konsumlamm commented on doc/lib.rst
> +  This module contains code for reading from stdin. On UNIX the linenoise library is wrapped and set up to provide default key bindings (e.g. you can navigate with the arrow keys). On Windows system.
```suggestion
  This module contains code for reading from stdin.
```
I think this is enough.

2021-03-20 18:01 UTC, konsumlamm commented on doc/lib.rst
> +  This module implements a hookable (de)serialization for arbitrary types. Design goal: avoid importing modules where a custom serialization is needed; see strtabs.fromJsonHook,toJsonHook for an exam
```suggestion
  This module implements a hookable (de)serialization for arbitrary types.
```

2021-03-20 18:01 UTC, konsumlamm commented on doc/lib.rst
> +  This module implements a json parser. It is used and exported by the json standard library module, but can also be used in its own right.
```suggestion
  This module implements a JSON parser. It is used and exported by the `json` standard library module, but can also be used in its own right.
```

2021-03-20 18:01 UTC, konsumlamm commented on doc/lib.rst
> +  This module implements enumerate syntactic sugar based on Nim's macro system.
```suggestion
  This module implements `enumerate` syntactic sugar based on Nim's macro system.
```

2021-03-20 18:01 UTC, konsumlamm commented on doc/lib.rst
> +  This module implements the with macro for easy function chaining. See `<https://github.com/nim-lang/RFCs/issues/193>`_ and `<https://github.com/nim-lang/RFCs/issues/192>`_ for details leading to th
```suggestion
  This module implements the `with` macro for easy function chaining.
```

2021-03-20 18:05 UTC, konsumlamm commented on doc/lib.rst
> +  This module contains code for reading from stdin. On UNIX the linenoise library is wrapped and set up to provide default key bindings (e.g. you can navigate with the arrow keys). On Windows system.
Also, this should go under the `Impure libraries` section, just add a new sub-section there.

2021-03-20 18:07 UTC, konsumlamm commented
The modules should be ordered alphabetically and the modules in the `std` directory (`jsonutils`, `enumerate`, `with`) should have a `std/` prefix (at least until #16999 is merged).

2021-03-20 19:44 UTC, Yardanico commented on doc/lib.rst
> +  This module implements a json parser. It is used and exported by the json standard library module, but can also be used in its own right.
isn't "standard library" redundant?

```suggestion
  This module implements a JSON parser. It is used and exported by the `json` module, but can also be used in its own right.
```

2021-03-20 19:44 UTC, Yardanico commented on doc/lib.rst
> +  This module implements a json parser. It is used and exported by the json standard library module, but can also be used in its own right.
or we can actually make it a link to the json module

2021-03-20 20:56 UTC, konsumlamm commented on doc/lib.rst
> +  This module implements a json parser. It is used and exported by the json standard library module, but can also be used in its own right.
You're right, good idea.

2021-03-21 12:48 UTC, AFaurholt commented
Added the std/ and the other suggestions

2021-03-21 13:49 UTC, konsumlamm commented
See https://github.com/nim-lang/Nim/pull/17430#discussion_r598141532.

2021-03-21 13:55 UTC, AFaurholt commented
> 
> 
> See [#17430 (comment)](https://github.com/nim-lang/Nim/pull/17430#discussion_r598141532).

Should be fixed now. Thanks for the catch

2021-03-21 17:35 UTC, merged