follow up #15951
nim-lang/Nim pull request #17478
Opened 2021-03-23 15:31 UTC by xflywind

2021-03-23 18:05 UTC, konsumlamm requested changes

2021-03-23 18:05 UTC, konsumlamm commented on lib/std/strbasics.nim
> +  ## Checks whether or not `c` is a lower case character.
```suggestion
  ## Checks whether or not `c` is a lowercase ASCII character.
```

2021-03-23 18:05 UTC, konsumlamm commented on lib/std/strbasics.nim
> +  ## Checks whether or not `c` is an upper case character.
```suggestion
  ## Checks whether or not `c` is an uppercase ASCII character.
```

2021-03-23 18:06 UTC, konsumlamm commented
The new `proc`s could be `func`s as far as I can tell.

2021-03-24 07:13 UTC, timotheecour commented
will review tomorrow

2021-03-24 22:08 UTC, dom96 commented on lib/std/strbasics.nim
> +proc forceCopy*(result: var string, a: string) =
can't https://nim-lang.org/docs/system.html#deepCopy%2CT%2CT be used?

2021-03-25 03:33 UTC, Yardanico commented on lib/std/strbasics.nim
> +  # the naitve `result = a` would not work if `a` is shallow
```suggestion
  # the naive `result = a` would not work if `a` is shallow
```

2021-03-25 06:11 UTC, Araq commented
Are these useful "basics" though? I never used strutils2.nim.

2021-03-30 08:32 UTC, Araq commented
Sorry, rejected. Additions to `strbasics` must be done most carefully.

2021-03-30 08:32 UTC, closed without merging