Export sslHandle in `net` and `asyncnet`.
nim-lang/Nim pull request #17573
Opened 2021-03-29 16:38 UTC by ardek66

Fix https://github.com/nim-lang/Nim/issues/17021

2021-03-29 16:45 UTC, timotheecour approved these changes

2021-03-29 16:47 UTC, Yardanico approved these changes

2021-03-29 22:54 UTC, dom96 requested changes
Exporting means that we allow read/write, we shouldn't.

Turn this into an accessor (`getSslHandle`).

For reviewers: please don't merge such changes. Let's consider carefully what we want to expose.

2021-03-30 00:27 UTC, konsumlamm commented
> Turn this into an accessor (`getSslHandle`).

Why not just `sslHandle`?

2021-03-30 11:24 UTC, Yardanico commented on lib/pure/asyncnet.nim
> +    return socket.sslHandle
Nit: return is redundant :)

2021-03-30 15:42 UTC, timotheecour commented on lib/pure/asyncnet.nim
> +    return socket.sslHandle
```suggestion
  proc sslHandle*(self: AsyncSocket): SslPtr =
    ## Retrieve the ssl pointer of `self`.
    ## Useful for interfacing with `openssl`.
    self.sslHandle
```

2021-03-30 15:43 UTC, timotheecour commented on lib/pure/net.nim
> +    return socket.sslHandle
```suggestion
  proc sslHandle*(self: Socket): SslPtr =
    ## Retrieve the ssl pointer of `self`.
    ## Useful for interfacing with `openssl`.
    self.sslHandle
```

2021-03-30 16:20 UTC, timotheecour approved these changes

2021-03-30 22:53 UTC, dom96 requested changes
Why not just `sslHandle`? Well, there is a good reason for this: you avoid the risk of having an infinite loop because you call the proc again instead of the field. I have had this happen and I think this is good enough reason to adopt this as a convention and include the "get" prefix.

2021-03-30 23:00 UTC, timotheecour commented
> you avoid the risk of having an infinite loop because you call the proc again by accident instead of accessing the field

do you have a reproducible example?
this works:
```
type Foo = object
  bar: int
proc bar(a: Foo): int = a.bar
let a = Foo(bar: 3)
echo a.bar
echo bar(a)
```

2021-04-05 17:01 UTC, timotheecour commented
I'm adding a guideline in https://github.com/nim-lang/Nim/pull/17645 to discuss this, please comment in that PR

2021-05-03 15:35 UTC, ardek66 commented
@dom96

2021-05-03 16:17 UTC, dom96 commented
I don't recall the exact circumstances when this problem occurred, but other things to try are generics and defining these procs across module boundaries. I definitely had an infinite loop happen in the past which made me wary of naming the proc the same name as the field, even if it was a bug in the past it may be worthwhile to be defensive here (as reading the code itself can be confusing).

2021-05-03 17:23 UTC, ardek66 commented
@dom96 I tested it and it seems fields are checked before function calls.
https://play.nim-lang.org/#ix=3lHH
You can see that the function is only called at the second assignment of `bar`, when we explicitly write the call syntax.
I also tested it across modules, making a module with the type and proc definititions, and a program importing that and doing the calls.

```nim
# a.nim
type Foo* = object
  a*: int

proc a*(self: Foo): int =
  echo "the proc is called"
  return self.a
```
```nim
# b.nim
import a

var foo: Foo
foo.a = 3
var bar = foo.a
echo bar

bar = a(foo)
echo bar
```

Works exactly like the playground I presented above.
Knowing that fields are called before procs, I dont see why the ssl getter would lead into an infinite recursion error.

I think your infinite recursion was caused by the getter being defined in a context where you had a module in which an object was exported, but not the field the getter was supposed to wrap. Something like:
```nim
# a.nim

type Foo* = object
  a: int # Notice we didn't export this field
```

```nim
# b.nim
import a

var foo: Foo

proc a(foo: Foo): int =
  return foo.a # Since the field wasnt actually exported, this actually calls the procedure, resulting in an infinite loop

var bar = foo.a
echo bar

bar = a(foo)
echo bar

2021-05-06 07:54 UTC, ardek66 commented
To add to this even the manual states that the object field is preffered before the function call, so it shouldn't do recursion.
https://nim-lang.org/docs/manual.html#procedures-properties

2021-05-06 21:18 UTC, dom96 approved these changes
Since others are happy, feel free to merge :)

2021-05-06 22:02 UTC, merged