add `NotImplementedDefect`
nim-lang/Nim pull request #17649
Opened 2021-04-05 19:11 UTC by timotheecour

2021-04-06 12:06 UTC, Araq commented
I never really understood the pattern though... why not use ``.error : "n/a"`` instead?

2021-04-06 15:11 UTC, ehmry commented
I've tried to make these compile-time errors, but I've found that I do need them built, and that they don't get called at runtime in the common case (or in the common exotic case).

2021-04-06 15:59 UTC, Araq commented
Yes, I understand this much. But why is that?

2021-04-06 16:38 UTC, timotheecour commented
with `proc foo(){.error: "n/a".}`, you need to patch all clients of `foo` to statically avoid calling `foo`, you're just shifting the responsibility from 1 caller to N callers. Even if `foo` isn't called at RT.

Furthermore it's not DRY: you need to duplicate the logic as to what platforms need it disabled, and when some platform finally gets support for it, you then need to patch all N clients again.

```nim
when defined(genode) or defined(js) or defined(nintendoswitch):
  proc foo(){.error: "n/a".}
else:
  proc foo() = discard
proc bar(cond: bool) = # one of foo's N clients
  if cond:
    when defined(genode) or defined(js) or defined(nintendoswitch):
      doAssert false
      # static: doAssert false would be even worse, bubbling up to clients of `bar`
    else:
      foo()
```

with a RT defect (as in this PR), all you need is to patch the callee `foo`, not the N callers (which can live in 3rd party packages over which you have no control):
```nim
proc foo() =
  when defined(genode) or defined(js) or defined(nintendoswitch):
    raise newException(NotImplementedDefect, "")
  else: discard

proc bar(cond: bool) = # one of foo's N clients
  if cond: foo()
```

It's related to these cases with nimvm branch can't use {.error.}
* https://github.com/nim-lang/Nim/pull/17161#discussion_r582842004
* https://github.com/nim-lang/Nim/pull/17252#discussion_r587348522

2021-04-06 17:52 UTC, dom96 requested changes
The idea seems fine to me, but we shouldn't get rid of these useful error messages IMO

2021-04-06 17:52 UTC, dom96 commented on lib/pure/dynlib.nim
> +    raise newException(NotImplementedDefect, "")
Can you keep the error messages?

2021-04-06 17:57 UTC, Araq commented
> with proc foo(){.error: "n/a".}, you need to patch all clients of foo to statically avoid calling foo, you're just shifting the responsibility from 1 callee to N callers. Even if foo isn't called at RT.

There is no alternative to analysing the N callsites, moving the problem to RT simply means you spend the time in a debugger instead. That's worse.

2021-04-06 20:19 UTC, Araq commented
> Furthermore it's not DRY: you need to duplicate the logic as to what platforms need it disabled, and when some platform finally gets support for it (eg nodejs, genode etc), you then need to patch all N clients again.

Hardly. ``when declared(foo): foo()``. This means that leaving out the prototypes of unsupported procs is even better than ``.error``  though. Or you could use some ``when compiles`` variant.

2021-04-07 08:45 UTC, timotheecour commented
> There is no alternative to analysing the N callsites, moving the problem to RT simply means you spend the time in a debugger instead. That's worse.

## `{.error: "not implemented".}` is simply impractical and causes breaking changes.

Take for example this PR from today, https://github.com/nim-lang/Nim/pull/17662#discussion_r608294300; adding `{.error.}` makes CI fail in lots of places:
```nim
iterator walkDir*(...) = ... elif defined(js): {.error: "not implemented for JS backend".}
```
to fix it with the `{.error.}` approach, you'd need to find all clients of `walkDir` and handle this somehow:
* either with a runtime error (in which you haven't improved anything over `raise NotImplementedDefect`)
* or with a CT error; it cannot be `static: doAssert false` which would prevent compilation, so it requires splitting each client (eg `walkDirRec`) into an `{.error.}` variant for unsupported backends and an actual implementation for supported backends.
* And then you need to do that again for the clients (eg `walkDirRec`) that turned into {.error.}, recursively.
* And after doing that, you've broken perfectly valid existing 3rd party packages which now do not compile anymore with the js/unsupported backend even if they never called that unsupported API in the first place.

This is in fact similar to the arguments against requiring manually specifying `{.raises: X.}` on each API ala java ((refs https://www.artima.com/articles/the-trouble-with-checked-exceptions, http://www.gotw.ca/publications/mill22.htm, etc).


## leaving out the prototypes of unsupported procs + `when declared(foo): foo()`
this suffers from the same problems as `{.error.}`:
* it's viral (you'll need to recursively fixup A, then clients of A, then clients(clients(A)) etc
* it breaks perfectly valid existing 3rd party code on the unsupported backend even though they never called the unsupported API in question
* more generally, it adds a lot of churn for no real gain.

## proposal: 
We can achieve the best of both worlds (no churn, static checking), as follows, by leveraging the effect system:
* introduce `NotImplementedError` instead of `NotImplementedDefect` (this PR needs to be updated accordingly; i think Error instead of Defect is reasonable).

then this proc is implicitly inferred as `{.raises: [NotImplementedError].}` on js backend only:
```nim
proc fn() =
  when defined(js): raise newException(NotImplementedError, "")
  else: ...
proc fn2() = # client of `fn`
  for i in 0..<3: fn()
```
then fn2 is also implicitly inferred as `{.raises: [NotImplementedError].}` on js backend only, but note that the source code didn't need any modification => no churn 
* for the special case of fwd declarations, you'd need `{.raises: [NotImplementedError].}`for now, but I've argued in https://github.com/nim-lang/Nim/issues/17462 that it's entirely possibly to do effect inference on fwd declarations

* finally, the compiler can issue a warning when compiler determines that reachable code for a full program (or reachable code for an `{.exportc, dynlib.}` API with `--app:lib`) can raise an uncaught `NotImplementedError`. This last point is more general and applies to any catchable exception.

## benefits
* no churn; when considering a new backend on a code that wasn't initially designed for it or doesn't yet support it (eg `walkDir` for `js`, or `nimLoadLibrary` for `genode`), you'll only need to annotate the leaf APIs with `raise newException(NotImplementedError, "")` on unsupported backends; the direct or indirect clients don't need to be aware of any of this. This is an important point!
* the `NotImplementedError` exceptions are tracked through call graph all the way to program/dll entry point, and a warning can be issued if compiler determines reachability from entry point to a raised `NotImplementedError`.

2021-04-07 18:07 UTC, Araq commented
But currently we cannot even write ``.raises: [not NotImplementedError]``. I prefer my solution, if at compile-time you know that something is not supported, don't offer it. Simple. Yeah, yeah, "code silos". I prefer the code silo solution over the complexity.

2022-05-31 02:25 UTC, closed without merging

2023-04-15 14:02 UTC, metagn commented
Really weird that no one mentioned the biggest use case, things that work in the VM but not at runtime