Fix for #18161 AsyncHttpServer Issue: Too many open files, against devel branch.
nim-lang/Nim pull request #18205
Opened 2021-06-06 20:21 UTC by mrhdias

The client header "connection" if equal to "keep-alive" is disabled whenever the number of file descriptors exceeds the specified maxFDs or exceeds the keep-alive timeout.
If the value of header "connection" equal "close", the connection is closed, if it is "keep-alive" it remains open and the number of file descriptors increases and the server die.
To avoid this issue the "keep-alive" connection is disabled. It is temporary until the number of files descriptors goes down, when the value goes down the connection can remain open. It also solves the issue when the "connection" is equal to "update".

2021-06-06 20:33 UTC, dom96 requested changes
Please see my comment in https://github.com/nim-lang/Nim/issues/18161#issuecomment-855458216 on what the approach should be.

2021-06-06 20:59 UTC, mrhdias commented
> Please see my comment in [#18161 (comment)](https://github.com/nim-lang/Nim/issues/18161#issuecomment-855458216) on what the approach should be.

I took a look at the asyncdispatch file and I think the activeDescriptors function doesn't read the real number of open file descriptors!
The following function gives the actual number of open file descriptors for the process, but it's slow!
```nim
import posix
import strutils
import os

proc getFdForProcess(pid: int): int =
  var count = 0
  for path in walkPattern("/proc/$1/fd/[0-9]*" % $pid):
    inc(count)

  return count

let pid = getpid()
echo getFdForProcess(pid)
```

2021-06-06 22:04 UTC, dom96 commented
Yes, and you can do that by following what I suggest.

2021-06-07 01:55 UTC, timotheecour commented
> The following function gives the actual number of open file descriptors for the process, but it's slow!

did you measure? for me it's 3s per 1M calls, ie 3us per call; compared to typical network latencies (with order of magnitude of 10ms or 100ms), this is nothing; furthermore it could be cached for a small duration if needed for extra performane.

benchmark:
nim r -d:release main
(3.557653119, 4000000)
```nim
import std/[posix, strutils, os, times]
proc getFdForProcess(pid: int): int =
  for path in walkPattern("/proc/$1/fd/[0-9]*" % $pid):
    result.inc
proc main =
  let pid = getpid()
  let n = 1000000
  var c = 0
  let t = cpuTime()
  for i in 0..<n:
    c += getFdForProcess(pid)
  let t2 = cpuTime()
  echo (t2 - t, c)
main()
```

2021-06-07 03:11 UTC, timotheecour commented on lib/pure/asynchttpserver.nim
> +                         maxBody = 8388608, keepaliveTimeout = 3600): AsyncHttpServer =
see also: https://github.com/nim-lang/RFCs/issues/383

2021-06-11 17:06 UTC, mrhdias commented
> > The following function gives the actual number of open file descriptors for the process, but it's slow!
> 
> did you measure? for me it's 3s per 1M calls, ie 3us per call; compared to typical network latencies (with order of magnitude of 10ms or 100ms), this is nothing; furthermore it could be cached for a small duration if needed for extra performane.
> 
> benchmark:
> nim r -d:release main
> (3.557653119, 4000000)
> 
> ```nim
> import std/[posix, strutils, os, times]
> proc getFdForProcess(pid: int): int =
>   for path in walkPattern("/proc/$1/fd/[0-9]*" % $pid):
>     result.inc
> proc main =
>   let pid = getpid()
>   let n = 1000000
>   var c = 0
>   let t = cpuTime()
>   for i in 0..<n:
>     c += getFdForProcess(pid)
>   let t2 = cpuTime()
>   echo (t2 - t, c)
> main()
> ```

I took a look at python "psutils" package and has the "num_fds" function that gives he number of file descriptors currently opened for every OS.

#!/usr/bin/python

# https://psutil.readthedocs.io/en/latest/#psutil.Process.num_fds
# https://github.com/giampaolo/psutil/blob/master/psutil/_pslinux.py#L2135

import psutil

p = psutil.Process()
print(p.num_fds())

2022-07-13 18:23 UTC, closed without merging