add macros.getChildPtr; add wrapnils.checkNil
nim-lang/Nim pull request #18559
Opened 2021-07-22 20:38 UTC by timotheecour

## add `macros.getChildPtr`
it allows returning a ptr to ith child of a NimNode (`n[i]` itself doesn't have an address so `n[i].addr` or `n[i].unsafeAddr` can't be used).
It's useful when you need to operate recursively on children of a NimNode and tracking the parent and index (and in fact the path from root node, eg `n[1][2][0]`) so a sub-node can be re-assigned is either not possible or makes the code much more complex.

## add `wrapnils.checkNil`
wrapnils only checks for nil dereferences (ptr-like types) and field checks (variant types), but it doesn't check whether an argument passed to a proc is nil, since the proc could accept nil inputs and wrapnils has no way to know that. This PR adds an API `checkNil` which ensures that a sub-expression is not nil before being passed to a proc, making the check explicit in the call chain.

It uses `getChildPtr`, which allows to get rid of tracking the parent `var old: tuple[n: NimNode, index: int]` (which was used for discriminant field checks, since https://github.com/nim-lang/Nim/pull/18435) and also enables implementing `checkNil` in a much simpler way than if `getChildPtr` were not available; in fact, I was not able to implement `checkNil` without it.

## Examples
see tests in tests/stdlib/twrapnils.nim and example in lib/std/wrapnils.nim

2021-07-23 21:01 UTC, Varriount requested changes

2021-07-23 21:01 UTC, Varriount commented on lib/core/macros.nim
> +proc getChildPtr*(n: NimNode, i: int): ptr NimNode =
Rather than a function, would it be possible to implement a way where `n[i].addr` would simply work? Why doesn't it currently work?

Additionally, what use-cases are there for using a pointer to a macro?

2021-07-23 21:01 UTC, Varriount commented on lib/std/wrapnils.nim
> +proc checkNil*[T: ptr|ref|cstring|proc](a: T): T {.inline.} =
Could you elaborate on what this does a bit more? I thought the whole point of `?.` was to return a default value in case of a nil expression.

2021-09-06 16:25 UTC, Araq commented
This encourages macro writers to be even less disciplined in their macro code. Rejected.

2021-09-06 16:25 UTC, closed without merging