Introduce urlencodeIRI and safeParseUri
nim-lang/Nim pull request #19128
Opened 2021-11-12 01:33 UTC by FedericoCeratto

Parse URI/IRI with some degree of safety.

Related to #17967 and https://github.com/nim-lang/security/security/advisories/GHSA-3gg2-rw3q-qwgc

2021-11-13 01:59 UTC, Varriount commented
Is there a reason why the existing `parseUri` function can't be updated?

2021-11-13 15:53 UTC, FedericoCeratto commented
@Varriount: Araq did not want to break the existing behavior by introducing an exception and rolled back https://github.com/nim-lang/Nim/pull/17967

2021-11-14 00:11 UTC, Varriount commented
@Araq So existing applications become insecure, rather than being fixed? I'd much rather a program fail with an exception, than be silently insecure.

2021-11-14 08:22 UTC, arnetheduck commented
> So existing applications become insecure, rather than being fixed

They don't "become" insecure - they remain as they were: if they  doing their own validation up-front, as is common in applications that take user input validation seriously, they continue to work.

If they were affected, they need to be reviewed manually because a new exception may introduce _new_ security issues that are worse, such as resources exhaustion or unintended behaviors due to the altered control flow that an exception causes - there's no way around this, ergo the function gets a deprecation warning to allow the owner of the library or application to make a judgment.

2021-11-14 18:37 UTC, dom96 requested changes
The original exploit focuses on null bytes. Sure, we can solve that with an exception, but it seems to me like we have another option: just stop reading bytes after `\0` (null).

The new `safeParseUri` proc in this PR seems to just add validation on top of the parser which already only reads the set of characters that are allowed in each URI part. I would just patch that instead of adding this new validation.

2021-11-14 18:40 UTC, dom96 commented
Could we just do something as simple as this? https://github.com/nim-lang/Nim/pull/19148

2021-11-15 14:43 UTC, Araq commented
> So existing applications become insecure, rather than being fixed? I'd much rather a program fail with an exception, than be silently insecure. Also, what happens if this new version has a bug? Do we come out with a "safeParseUriReal` procedure, a la PHP?

No, then we fix the proc, but this time it's already allowed to raise an exception so that no type signature did change. Which brings us to a viable alternative: Make it return an `Option[T]`, then the code breakage is obvious and for everybody to see. It's a breaking change though then. I don't mind breaking changes if they affect security and are detectable at compile-time.

2021-11-15 20:51 UTC, Varriount commented
> 
> 
> > So existing applications become insecure, rather than being fixed? I'd much rather a program fail with an exception, than be silently insecure. Also, what happens if this new version has a bug? Do we come out with a "safeParseUriReal` procedure, a la PHP?
> 
> No, then we fix the proc, but this time it's already allowed to raise an exception so that no type signature did change.

Why is a changed type signature a prerequisite for a breaking change?

2021-11-16 09:27 UTC, Varriount commented
> If they were affected, they need to be reviewed manually because a new exception may introduce new security issues that are worse, such as resources exhaustion or unintended behaviors due to the altered control flow that an exception causes - there's no way around this, ergo the function gets a deprecation warning to allow the owner of the library or application to make a judgment.

How often does something like this actually occur, realistically speaking? By this reasoning, nearly *any* change in a routine's logic world be considered a breaking change, as *nearly all* implementation changes can lead to altered control flow by the routine's callers.

Adding a new exception will, in

2021-12-03 12:28 UTC, FedericoCeratto commented
> @dom96: "Sure, we can solve that with an exception, but it seems to me like we have another option: just stop reading bytes after \0 (null)."

Recovering quietly from malicious input is not a good security practice. E.g. can be leveraged by attackers to mislead users. Suspicious inputs should be detected as early as possible and prevented from going deeper down the code path.

Also, when writing parsers/validators looking specifically for some invalid content is a dangerous method sometimes called "enumerating badness". Instead one should assume that the input is malicious unless it's proven that contains only valid data.

2021-12-03 15:19 UTC, dom96 commented
@FedericoCeratto I don't understand why this is necessarily malicious input. Like how can this be exploited?

There is by the way lots of stdlib procs that completely ignore `\0`, first example that came to mind:

```nim
import os

var x = "foo/bar\0path.txt"
echo(repr(x / "baz")) # 0x7f9850df2060"foo/bar\0path.txt/baz"
```

Should we make these procs throw too?

2021-12-17 11:10 UTC, dom96 requested changes
We discussed this starting at https://discord.com/channels/371759389889003530/768367394547957761/921343502690959370

IMO what this comes down to is that the URI parser was correct, it should accept `\0`. I tested Python and it appears to parse URIs containing `\0` just fine, without any exceptions. **This implies that we should revert https://github.com/nim-lang/Nim/pull/19148.**

Since the URI spec doesn't seem to mind \0 and it's feasible that some oddball software might be expecting to work with null bytes in the URL, I think it's fair to keep this support.

IMO what this PR should introduce is an explicit `validate` proc and nothing else. We should also make httpclient use it. We can also add a warning to the url parse proc to mention the `validate` proc.

2021-12-23 20:27 UTC, quantimnot commented
I've been experimenting with a PEG-based IRI parser. Null is only allowed when percent encoded. Here is a PEG for IRIs that I translated from the specs:
```
# https://tools.ietf.org/html/rfc3986#appendix-A
# https://tools.ietf.org/html/rfc3987#section-2.2
# https://www.rfc-editor.org/errata_search.php?rfc=3986
# https://tools.ietf.org/id/draft-ietf-iri-4395bis-irireg-04.html#rfc.section.3.6

URI_reference  <- URI / relative_ref / suffixRef

URI       <- ^ scheme ":" hier_part ("?" query )? ("#" fragment)? $

hier_part    <- "//" authority path_abempty
                / path_absolute
                / path_rootless
                / path_empty

suffixRef    <- authority path_abempty

relative_ref  <- ^ relative_part ("?" query)? ("#" fragment)? $

relative_part  <- "//" authority path_abempty
                / path_absolute
                / path_noscheme
                / path_empty

scheme     <- ALPHA (ALPHA / \d / "+" / "-" / "." )* &":"

authority    <- (userinfo "@")? host (":" port)?
userinfo    <- ((!"@" unreserved) / pct_encoded / sub_delims / ":")+ &"@"
host      <- IP_literal / IPv4address / reg_name
port      <- \d+

IP_literal <- "[" ( IPv6address / IPv6addrz / IPvFuture  ) "]"

IPvFuture <- "v" HEXDIGIT+ "." (unreserved / sub_delims / ":")+

IPv6address <-  h16 ":" h16 ":" h16 ":" h16 ":" h16 ":" h16 ":" ls32
                        / "::" h16 ":" h16 ":" h16 ":" h16 ":" h16 ":" ls32
                        / h16? "::" h16 ":" h16 ":" h16 ":" h16 ":" ls32

                        / ((h16 ":")? h16)? "::" h16 ":" h16 ":" h16 ":" ls32

                        / [ *2( h16 ":" ) h16 ] "::" h16 ":" h16 ':' ls32
                        / [ *3( h16 ":" ) h16 ] "::" h16 ":" ls32
                        / [ *4( h16 ":" ) h16 ] "::" ls32
                        / [ *5( h16 ":" ) h16 ] "::" h16
                        / [ *6( h16 ":" ) h16 ] "::"

ZoneID <- ( unreserved / pct_encoded )+
IPv6addrz <- IPv6address "%25" ZoneID
# IPv6 zone support was added in RFC6874.
# See: file://./doc/rfc6874.txt

h16 <- HEXDIGIT (HEXDIGIT (HEXDIGIT HEXDIGIT?)?)?
ls32 <- h16 ":" h16 / IPv4address
IPv4address <- dec_octet "." dec_octet "." dec_octet "." dec_octet

dec_octet <- \d         # 0-9
          / [\x31-\x39] \d   # 10-99
          / "1" \d \d      # 100-199
          / "2" [\x30-\x34] \d # 200-249
          / "25" [\x30-\x35]  # 250-255

reg_name <- ( unreserved / pct_encoded / "-" / "." )*

path_abempty <- ( "/" segment )*
path_absolute <- "/" ( segment_nz ( "/" segment )* )?
path_noscheme <- segment_nz_nc ( "/" segment )*
path_rootless <- segment_nz ( "/" segment )*
path_empty <- ""

segment <- pchar*
segment_nz <- pchar+
segment_nz_nc <- ( unreserved / pct_encoded / sub_delims / "@" )+
                        # ; non-zero-length segment without any colon ":"

pchar <- unreserved / pct_encoded / sub_delims / ":" / "@"

query <- ( pchar / iprivate / "/" / "?" )*

fragment <- ( pchar / "/" / "?" )*

pct_encoded <- "%" HEXDIGIT HEXDIGIT

unreserved <- ALPHA / \d / "-" / "." / "_" / "~" / (!reserved ucschar)

ucschar <- [\xA0-\xD7FF] / [\xF900-\xFDCF] / [\xFDF0-\xFFEF]
            / [\x10000-\x1FFFD] / [\x20000-\x2FFFD] / [\x30000-\x3FFFD]
            / [\x40000-\x4FFFD] / [\x50000-\x5FFFD] / [\x60000-\x6FFFD]
            / [\x70000-\x7FFFD] / [\x80000-\x8FFFD] / [\x90000-\x9FFFD]
            / [\xA0000-\xAFFFD] / [\xB0000-\xBFFFD] / [\xC0000-\xCFFFD]
            / [\xD0000-\xDFFFD] / [\xE1000-\xEFFFD]

iprivate <- [\xE000-\xF8FF] / [\xF0000-\xFFFFD] / [\x100000-\x10FFFD]

reserved <- gen_delims / sub_delims
gen_delims <- ":" / "/" / "?" / "#" / "[" / "]" / "@"
sub_delims <- "!" / "$" / "&" / "'" / "(" / ")"
                        / "*" / "+" / "," / ";" / "="
HEXDIGIT <- [0-9a-fA-F]
ALPHA <- \a
```

2022-07-12 12:19 UTC, FedericoCeratto commented
@dom96 @Araq There's been no progress on the vulnerability for a while. Based on the thumbs up in the last message it seems you both want to resurrect https://github.com/nim-lang/Nim/pull/19148 (and abandon this PR and https://github.com/nim-lang/Nim/pull/17967)
Is that correct? If so, who's going to do it?

2022-07-12 15:57 UTC, Araq commented
https://github.com/nim-lang/Nim/pull/19148 has been reverted for quite some time. I have no intention of bringing it back. We can discuss "what is a valid URL?" here or elsewhere and fix it for version 2.0 but it should be based on specifications and best practices. For example, "URLs cannot contain whitespace where whitespace is defined as `{'\0'..'\32'}`" would be a solid rule. As would be "it's not the uri.nim's job to do validation at all".

2024-04-23 00:36 UTC, closed without merging