fix #19500; remove find optimization [backport: 1.6]
nim-lang/Nim pull request #19714
Opened 2022-04-12 04:39 UTC by ringabout

fix https://github.com/nim-lang/Nim/issues/19500
close https://github.com/nim-lang/Nim/pull/19504

2022-06-20 20:20 UTC, konsumlamm requested changes

2022-06-20 20:20 UTC, konsumlamm commented on lib/std/private/strimpl.nim
> +  ## Searches for `sub` in `s` inside range `start..last` (both ends included).
```suggestion
  ## Searches for `sub` in `s` inside the range `start..last` (both ends included).
```

2022-06-20 20:20 UTC, konsumlamm commented on lib/std/private/strimpl.nim
> +  ## Searches for `sub` in `s` inside range `start..last` (both ends included).
```suggestion
  ## Searches for `sub` in `s` inside the range `start..last` (both ends included).
```

2022-09-25 19:32 UTC, Varriount commented
Just to ensure I understand the changes correctly, how is this different from https://github.com/nim-lang/Nim/pull/19504 ?

2022-09-26 05:08 UTC, ringabout commented on lib/std/private/strimpl.nim
> +  return -1
Not much, I just kept changes in the private modules.

2022-09-28 20:05 UTC, Varriount approved these changes

2022-09-28 20:05 UTC, merged

2022-09-29 01:31 UTC, ringabout commented
Since it has been merged, I will use memmem to optimize it later.