add test case for #7839
nim-lang/Nim pull request #20682
Opened 2022-10-27 16:38 UTC by bung87

close #7839

2023-01-18 21:34 UTC, Araq commented
Why is the CI red?

2023-01-26 01:36 UTC, ringabout commented on tests/generics/t7839.nim
> +action: compile
```suggestion
action: run
```

2023-01-26 01:38 UTC, ringabout requested changes

2023-01-26 01:38 UTC, ringabout commented on tests/generics/t7839.nim
> +echo A.sizeof # works without the following proc
```suggestion
doAssert A.sizeof == 8 # works without the following proc
```

2023-01-26 01:38 UTC, ringabout commented on tests/generics/t7839.nim
> +"""
```suggestion
```

2023-05-01 17:35 UTC, metagn commented on tests/generics/t7839.nim
> +doAssert A.sizeof == 8 # works without the following proc
```suggestion
doAssert A.sizeof == sizeof(int) # works without the following proc
```

2023-06-02 21:30 UTC, metagn commented
This seems uncontroversial at this point, just remake as a new PR

2023-06-05 05:54 UTC, bung87 commented
replaced by https://github.com/nim-lang/Nim/pull/22006

2023-06-05 05:54 UTC, closed without merging