add getDataDir to std/appdirs.nim
nim-lang/Nim pull request #21754
Opened 2023-04-29 08:51 UTC by Ecorous

This PR extends #21408 by adding the `getDataDir` proc to the file `lib/std/appdirs.nim`

2023-04-29 13:32 UTC, Araq commented
CI is failing for some reason but appart from that it is acceptable.

2023-04-29 15:52 UTC, Ecorous commented
> CI is failing for some reason but appart from that it is acceptable.

It did that on #21408 as well. Not sure why it did. Never ended up fixing it

2023-04-29 17:22 UTC, Yardanico commented
In this PR the error seems to actually be relevant - 
![image](https://user-images.githubusercontent.com/21169548/235315445-3b0fa175-28dd-4612-a3ee-22e6334a2fb0.png)

The `/` proc for string + string is defined in `std/os`, not in `std/paths`

Also, aren't rtl and extern wrong here?

2023-04-29 17:24 UTC, Yardanico commented
Wait, at this point I'm really confused. Why do we have https://github.com/nim-lang/Nim/blob/devel/lib/std/private/osappdirs.nim and https://github.com/nim-lang/Nim/blob/devel/lib/std/appdirs.nim that both implement exactly the same things?

2023-04-30 04:20 UTC, ringabout commented
@Yardanico because `std/appdirs` introduces `Path` interface, which introduces breaking changes. `std/private/osappdirs` is used for std/os. I don't merge these two modules to keep backwards compatibility.

2023-05-11 12:24 UTC, ringabout requested changes

2023-05-11 12:24 UTC, ringabout commented on lib/std/appdirs.nim
> +  result.normalizePathEnd(trailingSep = true)
```suggestion
  result = Path(osappdirs.getDataDir())
```

2023-05-11 12:25 UTC, ringabout commented on lib/std/appdirs.nim
> +  result.normalizePathEnd(trailingSep = true)
Please reuse the implementation of https://github.com/nim-lang/Nim/blob/fe98cea9cff03cfbb32374208e83b9817694bf1c/lib/std/private/osappdirs.nim#L28

2023-05-12 11:08 UTC, ringabout commented on lib/std/appdirs.nim
> +  tags: [ReadEnvEffect, ReadIOEffect].} =
```suggestion
proc getDataDir*(): Path {.inline, tags: [ReadEnvEffect, ReadIOEffect].} =
```

2023-05-12 11:08 UTC, ringabout commented on lib/std/appdirs.nim
> +  tags: [ReadEnvEffect, ReadIOEffect].} =
```suggestion
proc getDataDir*(): Path {.inline, tags: [ReadEnvEffect, ReadIOEffect].} =
```

2023-05-12 11:09 UTC, ringabout approved these changes
LGTM. Since it's a new module, it doesn't need a changelog entry for a single proc.

2023-05-12 12:44 UTC, merged